Repository campaslab/napari-stress, pull requests merged in 2022-08, with the labels that each got.

#120 Create jupyter book
  .github/workflows/build_book.yml
  docs/_config.yml
  docs/_toc.yml
  docs/glossary/01_spherical_harmonics.md
  docs/glossary/02_analyzing_spherical_harmonics.md
  docs/glossary/Readme.md
  docs/intro.md
  docs/logo.png
  docs/tutorials/demo/Readme.md
  docs/tutorials/point_and_click/Readme.md
  docs/tutorials/point_and_click/demo_fit_ellipsoid.md
  docs/tutorials/point_and_click/demo_spherical_harmonics.md
  docs/tutorials/point_and_click/demo_surface_reconstruction.md
  requirements.txt
Labels: documentation

#122 Add documentation for curvature
  docs/_toc.yml
  docs/glossary/02_analyzing_spherical_harmonics.md
  docs/tutorials/demo/demo_analyze_spherical_harmonics.ipynb
  docs/tutorials/point_and_click/demo_measure_curvature.md
  docs/tutorials/point_and_click/demo_spherical_harmonics.md
  docs/tutorials/point_and_click/imgs/demo_measure_curvature1.png
  docs/tutorials/point_and_click/imgs/demo_measure_curvature2.png
  docs/tutorials/point_and_click/imgs/demo_measure_curvature3.png
  src/napari_stress/_measurements/curvature.py
Labels: documentation

#131 Moved coordinate conversion functions to single file
  src/napari_stress/_approximation/fit_ellipsoid.py
  src/napari_stress/_approximation/utils.py
  src/napari_stress/_spherical_harmonics/spherical_harmonics.py
  src/napari_stress/_tests/test_approximation.py
  src/napari_stress/_utils/coordinate_conversion.py
Labels: enhancement, nice to have

#132 Plot layer features
  setup.cfg
  src/napari_stress/__init__.py
  src/napari_stress/_plotting/features_histogram.py
  src/napari_stress/_tests/test_plotting.py
  src/napari_stress/napari.yaml
Labels: enhancement

#134 Add documentation
  docs/tutorials/point_and_click/demo_visualize_features.md
  docs/tutorials/point_and_click/imgs/demo_visualize_features1.png
  docs/tutorials/point_and_click/imgs/demo_visualize_features2.png
  docs/tutorials/point_and_click/imgs/demo_visualize_features3.png
Labels: documentation

#139 removed fit error from lebedev quadrature points features
  src/napari_stress/_spherical_harmonics/spherical_harmonics_napari.py
Labels: bug

#140 replace metadata fields by centrally defined strings
  src/napari_stress/_measurements/curvature.py
  src/napari_stress/_measurements/stresses.py
  src/napari_stress/_tests/test_approximation.py
  src/napari_stress/_tests/test_measurements.py
  src/napari_stress/types.py
Labels: enhancement

#143 Anisotropic stresses
  docs/_toc.yml
  docs/tutorials/demo/demo_anisotropic_stresses.ipynb
  src/napari_stress/_measurements/__init__.py
  src/napari_stress/_measurements/stresses.py
  src/napari_stress/_measurements/utils.py
  src/napari_stress/_tests/test_measurements.py
  src/napari_stress/napari.yaml
  src/napari_stress/types.py
Labels: core functionality

#145 Update layer `face_color` from feature visualization widget
  docs/tutorials/demo/demo_anisotropic_stresses.ipynb
  src/napari_stress/_measurements/__init__.py
  src/napari_stress/_measurements/curvature.py
  src/napari_stress/_plotting/features_histogram.py
Labels: enhancement

#146 replaced `orientation_matrix` calculation by function-internal calculation
  docs/tutorials/demo/demo_anisotropic_stresses.ipynb
  src/napari_stress/_measurements/stresses.py
  src/napari_stress/_tests/test_measurements.py
Labels: core functionality

#147 Add 4d pointcloud
  src/napari_stress/__init__.py
  src/napari_stress/_sample_data.py
  src/napari_stress/_tests/test_sample_data.py
  src/napari_stress/napari.yaml
  src/napari_stress/sample_data/dropplet_point_cloud_4d.csv
Labels: enhancement, nice to have
